# Generated by Django 3.2.7 on 2021-09-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('niveau', models.CharField(choices=[('TC1', 'TC1'), ('TC2', 'TC2'), ('DIC1', 'DIC1'), ('DIC2', 'DIC2'), ('DIC3', 'DIC3')], max_length=30)),
                ('gender', models.CharField(choices=[('H', 'HOMME'), ('F', 'FEMME')], max_length=30)),
                ('codifie', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='EtudiantPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_paye', models.CharField(choices=[('JANVIER', 'JANVIER'), ('FEVRIER', 'FEVRIER'), ('MARS', 'MARS'), ('AVRIL', 'AVRIL'), ('MAI', 'MAI'), ('JUIN', 'JUIN'), ('JUILLET', 'JUILLET'), ('AOUT', 'AOUT'), ('SEPTEMBRE', 'SEPTEMBRE'), ('OCTOBRE', 'OCTOBRE'), ('NOVEMBRE', 'NOVEMBRE'), ('DECEMBRE', 'DECEMBRE')], max_length=30)),
                ('date_payment', models.DateField(auto_now_add=True)),
                ('montant_paye', models.IntegerField(max_length=30)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='RestApiServer.etudiant')),
            ],
            options={
                'ordering': ('date_payment',),
            },
        ),
    ]
