# Generated by Django 3.2.7 on 2021-09-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0002_alter_etudiantpayment_montant_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantpayment',
            name='montant_paye',
            field=models.IntegerField(max_length=30),
        ),
    ]
