# Generated by Django 3.2.7 on 2021-09-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0003_alter_etudiantpayment_montant_paye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiantpayment',
            name='mois_paye',
            field=models.CharField(choices=[('JANVIER', 'JANVIER'), ('FEVRIER', 'FEVRIER'), ('MARS', 'MARS'), ('AVRIL', 'AVRIL'), ('MAI', 'MAI'), ('JUIN', 'JUIN'), ('JUILLET', 'JUILLET'), ('AOUT', 'AOUT'), ('SEPTEMBRE', 'SEPTEMBRE'), ('OCTOBRE', 'OCTOBRE'), ('NOVEMBRE', 'NOVEMBRE'), ('DECEMBRE', 'DECEMBRE')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiantpayment',
            name='montant_paye',
            field=models.IntegerField(),
        ),
    ]
