# Generated by Django 3.2.7 on 2021-09-16 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0004_auto_20210916_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pavillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavillon_name', models.CharField(max_length=200, unique=True)),
                ('chef_pavillon', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pavillon_name',),
            },
        ),
        migrations.AlterField(
            model_name='etudiantpayment',
            name='mois_paye',
            field=models.CharField(choices=[('JANVIER', 'JANVIER'), ('FEVRIER', 'FEVRIER'), ('MARS', 'MARS'), ('AVRIL', 'AVRIL'), ('MAI', 'MAI'), ('JUIN', 'JUIN'), ('JUILLET', 'JUILLET'), ('AOUT', 'AOUT'), ('SEPTEMBRE', 'SEPTEMBRE'), ('OCTOBRE', 'OCTOBRE'), ('NOVEMBRE', 'NOVEMBRE'), ('DECEMBRE', 'DECEMBRE')], max_length=30),
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chambre', models.IntegerField(unique=True)),
                ('etage', models.CharField(choices=[('RDC', 'REZ_DE_CHAUSSE'), ('1er', 'PREMIER_ETAGE'), ('2em', 'DEUXIEME_ETAGE')], max_length=30)),
                ('occupee', models.BooleanField(default=False)),
                ('pavillon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pavillon', to='RestApiServer.pavillon')),
            ],
            options={
                'ordering': ('numero_chambre',),
            },
        ),
    ]
