# Generated by Django 3.2.7 on 2021-09-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0005_auto_20210916_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='numero_chambre',
            field=models.IntegerField(),
        ),
    ]
