# Generated by Django 3.2.7 on 2021-09-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0006_alter_chambre_numero_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_codification', models.DateField(auto_now=True)),
                ('annee_scolaire', models.CharField(max_length=60)),
                ('Chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='RestApiServer.chambre')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RestApiServer.etudiant')),
            ],
            options={
                'ordering': ('date_codification',),
            },
        ),
    ]
