# Generated by Django 3.2.7 on 2021-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0007_codification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codification',
            name='date_codification',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='etudiantpayment',
            name='date_payment',
            field=models.DateField(),
        ),
    ]
