# Generated by Django 3.2.7 on 2021-09-18 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0008_auto_20210916_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='pavillon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='RestApiServer.pavillon'),
        ),
    ]
