# Generated by Django 3.2.7 on 2021-09-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0009_alter_chambre_pavillon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='etage',
            field=models.CharField(choices=[('REZ_DE_CHAUSSE', 'REZ_DE_CHAUSSE'), ('PREMIER_ETAGE', 'PREMIER_ETAGE'), ('DEUXIEME_ETAGE', 'DEUXIEME_ETAGE')], max_length=30),
        ),
    ]
