# Generated by Django 3.2.7 on 2021-09-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApiServer', '0011_alter_codification_etudiant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codification',
            old_name='Chambre',
            new_name='chambre',
        ),
    ]
